
id: am-imaging
version: 1.0.0
type: library
dependencies:
  - id: am-lang-core
    realm: github
    type: git-repo
    tag: latest
    branch: master
    url: https://github.com/anderskjeldsen/am-lang-core.git
platforms:
  - id: libc
    abstract: true
